# -*- mode: shell-script -*-
#
# Executes commands at login pre-zshrc.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

#
# Browser
#

if [[ "$OSTYPE" == darwin* ]]; then
  export BROWSER='open'
fi

#
# Editors
#

# prevent Emacs crash on Freya due to GTK+ bug
export XLIB_SKIP_ARGB_VISUALS=1
export EDITOR='emacsclient -c'
export ALTERNATE_EDITOR=''

# for proper colors in terminal when not inside tmux
if [[ -z $TMUX ]]; then
    export TERM=xterm-256color
fi

# export VISUAL='emacsclient -t -a ""'
export PAGER='less'

#
# Language
#

if [[ -z "$LANG" ]]; then
  export LANG='en_US.UTF-8'
fi

#
# Paths
#

# Ensure path arrays do not contain duplicates.
typeset -gU cdpath fpath mailpath path

# Set the the list of directories that cd searches.
# cdpath=(
#   $cdpath
# )

# Set the list of directories that Zsh searches for programs.
path=(
  ${HOME}/bin
  ${HOME}/.linuxbrew/bin
  ${HOME}/.local/bin
  /usr/local/heroku/bin
  /usr/local/cwb-3.4.8/bin
  /usr/local/{bin,sbin}
  $path
  # ${HOME}/htk/bin
  # ${HOME}/sbt/bin
  # ${HOME}/eclipse
  # ${HOME}/local/openfst-1.4.1/src/bin"
)

#
# Less
#

# Set the default Less options.
# Mouse-wheel scrolling has been disabled by -X (disable screen clearing).
# Remove -X and -F (exit if the content fits on one screen) to enable it.
export LESS='-F -g -i -M -R -S -w -X -z-4'

# Set the Less input preprocessor.
# Try both `lesspipe` and `lesspipe.sh` as either might exist on a system.
if (( $#commands[(i)lesspipe(|.sh)] )); then
  export LESSOPEN="| /usr/bin/env $commands[(i)lesspipe(|.sh)] %s 2>&-"
fi

#
# Temporary Files
#

if [[ ! -d "$TMPDIR" ]]; then
  export TMPDIR="/tmp/$LOGNAME"
  mkdir -p -m 700 "$TMPDIR"
fi

TMPPREFIX="${TMPDIR%/}/zsh"
